#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available. Otherwise it will execute while your application is stopped
# before the deploy step. This script gets executed directly, so it
# could be python, php, ruby, etc.
set -x
source $OPENSHIFT_REPO_DIR/.openshift/action_hooks/vars.inc
if [ -d $LIVEOAK_BASE ] ; then
  echo "Liveoak $LIVEOAK_VERSION has already been downloaded."
else
  cd $OPENSHIFT_DEPENDENCIES_DIR
  rm -Rf liveoak-dist-*
  wget -O $LIVEOAK_DOWNLOAD_FILE $LIVEOAK_DOWNLOAD_URL
  tar -xzf $LIVEOAK_DOWNLOAD_FILE
fi
