#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again. This script gets executed directly, so it could be python, php,
# ruby, etc.
set -x
source $OPENSHIFT_REPO_DIR/.openshift/action_hooks/vars.inc

# Copy standalone.conf to current installation.
cp -f $OPENSHIFT_REPO_DIR/liveoak/standalone.conf \
$LIVEOAK_BASE/bin/standalone.conf

# Copy keycloak to current installation.
cp -f $OPENSHIFT_REPO_DIR/liveoak/auth-server.war \
$LIVEOAK_BASE/standalone/deployments/auth-server.war
