#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
source $OPENSHIFT_REPO_DIR/.openshift/action_hooks/vars.inc
nohup $LIVEOAK_BASE/bin/standalone.sh > $OPENSHIFT_LOG_DIR/boot.log 2>&1 &
